source "https://rubygems.org"

gem "chupa-text"
gem "chupa-text-decomposer-pdf"
gem "chupa-text-decomposer-libreoffice-excel"
gem "chupa-text-decomposer-libreoffice-powerpoint"
gem "chupa-text-decomposer-libreoffice-word"
gem "rake"
