source "https://rubygems.org"

gem "git-commit-mailer", git: "https://gitlab.com/commit-email/git-commit-mailer.git"
gem "webhook-mailer", git: "https://gitlab.com/commit-email/webhook-mailer.git"
gem "racknga"
gem "rack"
