source "https://rubygems.org"

gem "git-commit-mailer", git: "https://gitlab.com/clear-code/git-commit-mailer.git"
gem "webhook-mailer", git: "https://gitlab.com/clear-code/webhook-mailer.git"
gem "racknga"
gem "rack"
