"https://webhook.commit-email.info/":
  events:
    - PushEvent
  repositories:
    - apache/arrow
    - apache/arrow-adbc
    - apache/arrow-dotnet
    - apache/arrow-flight-sql-postgresql
    - apache/arrow-js
    - apache/arrow-site
    - apache/arrow-skyhook
    - apache/arrow-swift
    - apache/arrow-testing
    - mruby/mruby
    - ruby/ruby
    - rurema/bitclust
    - rurema/doctree
